# Generated by Django 4.1 on 2023-02-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=25, verbose_name='Nombre')),
                ('address', models.TextField(max_length=60, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=60, verbose_name='Correo Electrónico')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='Sexo')),
                ('age', models.IntegerField(verbose_name='Edad')),
            ],
        ),
    ]
