# Generated by Django 4.1 on 2023-02-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Villian', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=60, verbose_name='Modelo')),
                ('trademark', models.TextField(max_length=60, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Character.automovil')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Villian.informacion')),
            ],
        ),
        migrations.CreateModel(
            name='AutomovilSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.TextField(max_length=60, verbose_name='Motor')),
                ('weight', models.TextField(max_length=60, verbose_name='Peso')),
                ('color', models.TextField(max_length=60, verbose_name='Color')),
                ('auto_need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Character.automovil')),
            ],
        ),
    ]
